[package]
name = "cobalto"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44", features = ["full"] }
log = "0.4"
regex = "1.11.1"
once_cell = "1.21.3"
notify = "8.0.0"
axum = { version = "0.8", features = ["ws"] }
futures = "0.3.31"
